[project]
name = "song-dl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "librosa>=0.11.0",
    "matplotlib>=3.10.1",
    "pydantic>=2.10.6",
    "streamlit>=1.43.2",
    "yt-dlp>=2025.3.21",
]
